### ISSUE TITLE
undefined: registry.ServiceConfig

### ISSUE THREAD

**Issue by DWay17** [jesseduffield/lazydocker#783]
**Describe the bug**
Can't install 0.25.0

**To Reproduce**
```log
$ go install github.com/jesseduffield/lazydocker@latest
go: downloading github.com/jesseduffield/lazydocker v0.25.0
# github.com/docker/docker/api/types/system
go/pkg/mod/github.com/docker/docker@v28.5.2+incompatible/api/types/system/info.go:51:31: undefined: registry.ServiceConfig
```

**Expected behaviour**
0.25 installed

**Comment by m5lk3n** [comment]
Same here, same with v0.25.2.

**Comment by 2005czq** [comment]
This appears to be the same issue as #711 and #723.
I was using the apt-installed Go 1.22.2 on Ubuntu, and after upgrading to 1.26.4 the issue resolved.
