### PR TITLE
Update golang.org/x/xerrors package (fixes go 1.13 builds)

### PR DESCRIPTION
**Pull request by mikhailswift**
Current master fails builds when building with go 1.13:

```
go: downloading golang.org/x/xerrors v0.0.0-20190513163551-3ee3066db522
go: extracting golang.org/x/xerrors v0.0.0-20190513163551-3ee3066db522
go: finding golang.org/x/xerrors v0.0.0-20190513163551-3ee3066db522
# golang.org/x/xerrors
../../go/pkg/mod/golang.org/x/xerrors@v0.0.0-20190513163551-3ee3066db522/adaptor_go1_13.go:16:14: undefined: errors.Frame
../../go/pkg/mod/golang.org/x/xerrors@v0.0.0-20190513163551-3ee3066db522/format_go1_13.go:12:18: undefined: errors.Formatter
```

Updating the golang.org/x/xerrors dependency fixes the issue, and still builds on go 1.12.

### CODE REVIEW

**Comment by dawidd6** [comment]
Did you ran `go mod vendor` too?

**Comment by mikhailswift** [comment]
Sorry, forgot you guys still use the vendor directory.  Updated it.

**Comment by dawidd6** [comment]
Thanks.
